# Generated by Django 3.2.5 on 2021-09-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='profile_photo'),
            preserve_default=False,
        ),
    ]
